
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class Add extends javax.swing.JInternalFrame {

    /**
     * Creates new form Add2
     */
    public Add() {
        initComponents();
        try {
            BufferedWriter f1 = new BufferedWriter(new FileWriter("MenuList.txt", true)); // true turns on the append mode
            f1.close();
            BufferedReader brSearch1 = new BufferedReader(new FileReader("MenuList.txt"));
            String key[] = new String[1024];
            String search;
            Object columns[] = {"Emp ID", "Name", "Salary", "Emp Shift"};
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columns);
            jTable1.setModel(model);
            Object row[] = new Object[4];
            while ((search = brSearch1.readLine()) != null) {

                key = search.split(",");
                row[0] = key[1];
                row[1] = key[2];
                row[2] = key[3];
                row[3] = key[4];
                model.addRow(row);
            }
            brSearch1.close();
        } catch (Exception ex) {
            System.out.println("Exception msg: " + ex);
        }
    }
    String nameSearchSel, id, name, salary, empshift, idSearchSel;
    //int cnt = 1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EmpID = new javax.swing.JLabel();
        EmpIDText = new javax.swing.JTextField();
        Salary = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Quality = new javax.swing.JLabel();
        SalaryText = new javax.swing.JTextField();
        NameText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Add Details");
        setPreferredSize(new java.awt.Dimension(1041, 525));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1025, 491));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EMPLOYEE DETAILS");
        jLabel1.setMaximumSize(new java.awt.Dimension(205, 29));
        jLabel1.setMinimumSize(new java.awt.Dimension(205, 29));
        jLabel1.setPreferredSize(new java.awt.Dimension(205, 29));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(330, 10, 454, 59);

        EmpID.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        EmpID.setForeground(new java.awt.Color(255, 255, 255));
        EmpID.setText("Emp ID");
        EmpID.setMaximumSize(new java.awt.Dimension(72, 20));
        EmpID.setMinimumSize(new java.awt.Dimension(72, 20));
        EmpID.setPreferredSize(new java.awt.Dimension(72, 20));
        jPanel1.add(EmpID);
        EmpID.setBounds(50, 140, 97, 28);

        EmpIDText.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        EmpIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIDTextActionPerformed(evt);
            }
        });
        jPanel1.add(EmpIDText);
        EmpIDText.setBounds(180, 146, 215, 40);

        Salary.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        Salary.setForeground(new java.awt.Color(255, 255, 255));
        Salary.setText("Salary");
        Salary.setMaximumSize(new java.awt.Dimension(72, 20));
        Salary.setMinimumSize(new java.awt.Dimension(72, 20));
        Salary.setPreferredSize(new java.awt.Dimension(72, 20));
        jPanel1.add(Salary);
        Salary.setBounds(40, 240, 97, 28);

        Name.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Name");
        Name.setMaximumSize(new java.awt.Dimension(72, 20));
        Name.setMinimumSize(new java.awt.Dimension(72, 20));
        Name.setPreferredSize(new java.awt.Dimension(72, 20));
        jPanel1.add(Name);
        Name.setBounds(50, 190, 97, 28);

        Quality.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        Quality.setForeground(new java.awt.Color(255, 255, 255));
        Quality.setText("Emp Shift");
        Quality.setMaximumSize(new java.awt.Dimension(72, 20));
        Quality.setMinimumSize(new java.awt.Dimension(72, 20));
        Quality.setPreferredSize(new java.awt.Dimension(72, 20));
        jPanel1.add(Quality);
        Quality.setBounds(40, 300, 128, 28);

        SalaryText.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(SalaryText);
        SalaryText.setBounds(180, 250, 215, 40);

        NameText.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(NameText);
        NameText.setBounds(180, 200, 215, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton1.setText("Add");
        jButton1.setMaximumSize(new java.awt.Dimension(125, 33));
        jButton1.setMinimumSize(new java.awt.Dimension(125, 33));
        jButton1.setPreferredSize(new java.awt.Dimension(125, 33));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(130, 400, 136, 49);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning", "Evening" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(210, 300, 121, 38);

        jTable1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp ID", "Name", "Salary", "Emp Shift"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(435, 90, 526, 402);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1110, 580);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            int result, flag = 0;
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            //Object[] columns = {"Emp ID", "Name", "Salary", "Emp Shift"};
            //model.setColumnIdentifiers(columns);
            //jTable1.setModel(model);
            Object[] row = new Object[4];
            row[0] = EmpIDText.getText().toUpperCase();
            row[1] = NameText.getText().toUpperCase();
            row[2] = SalaryText.getText().toUpperCase();
            row[3] = jComboBox1.getSelectedItem().toString().toUpperCase();
            model.addRow(row);
            //creating the files
            BufferedWriter bW1 = new BufferedWriter(new FileWriter("MenuList.txt", true));
            bW1.close();
            BufferedWriter ind = new BufferedWriter(new FileWriter("Index.txt", true));
            ind.close();
            BufferedWriter snd = new BufferedWriter(new FileWriter("Second_Index.txt", true));
            snd.close();

            //counting the number of records
//            BufferedReader brSearch0 = new BufferedReader(new FileReader("MenuList.txt"));
//            String recordSearch0;
//            while ((recordSearch0 = brSearch0.readLine()) != null) {
//                ++cnt;
//            }
//            brSearch0.close();
            //checking if name already exists
            if (NameText.getText().length() != 0) {
                BufferedReader br = new BufferedReader(new FileReader("MenuList.txt"));
                String recordSearch1;
                nameSearchSel = NameText.getText().toUpperCase();

                while ((recordSearch1 = br.readLine()) != null) {
                    if (recordSearch1.contains(nameSearchSel)) //checks if the name is already present or no
                    {
                        JOptionPane.showMessageDialog(null, "Name already exists!!");
                        flag = 1;
                    }
                }
                br.close();
            }

            //checking if id already exists
            if (EmpIDText.getText().length() != 0) {
                BufferedReader br = new BufferedReader(new FileReader("MenuList.txt"));
                String recordSearch1;
                String DisplaySearch0[] = new String[1024];

                idSearchSel = EmpIDText.getText().toUpperCase();
                int i1 = 0;
                while ((recordSearch1 = br.readLine()) != null) {
                    StringTokenizer stSearchView1 = new StringTokenizer(recordSearch1, ",");
                    if (recordSearch1.contains(idSearchSel)) //checks if the id is already present or no
                    {
                        JOptionPane.showMessageDialog(null, "ID already exists!!");
                        flag = 1;
                        i1++;
                    }
                }
                br.close();
            }
            //adding the details in the file
            if (flag != 1 && EmpIDText.getText().length() != 0 && NameText.getText().length() != 0 && SalaryText.getText().length() != 0) //if all the values are not entered
            {
                BufferedWriter bW2 = new BufferedWriter(new FileWriter("MenuList.txt", true));
                BufferedWriter b1 = new BufferedWriter(new FileWriter("Index.txt", true));
                BufferedWriter b2 = new BufferedWriter(new FileWriter("Second_Index.txt", true));
                id = EmpIDText.getText().toUpperCase();//textfields
                name = NameText.getText().toUpperCase();
                salary = SalaryText.getText();
                empshift = jComboBox1.getSelectedItem().toString().toUpperCase();//combobox
                result = id.charAt(id.length() - 1) - 48;
                bW2.write(result + "," + id + "," + name + "," + salary + "," + empshift);
                b1.write(result + "," + id);
                b2.write(id + "," + name + "," + salary + "," + empshift);
                JOptionPane.showMessageDialog(null, "detail successfully added!!");
                EmpIDText.setText("");
                NameText.setText("");
                SalaryText.setText("");
                bW2.flush();
                b1.flush();
                b2.flush();
                bW2.newLine();
                b1.newLine();
                b2.newLine();
                bW2.close();
                b1.close();
                b2.close();
            }
        } catch (Exception ex) {
            System.out.println("Exception msg: " + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void EmpIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpIDTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmpID;
    private javax.swing.JTextField EmpIDText;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameText;
    private javax.swing.JLabel Quality;
    private javax.swing.JLabel Salary;
    private javax.swing.JTextField SalaryText;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
