
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class Delete extends javax.swing.JInternalFrame {

    /**
     * Creates new form Search
     */
    public Delete() {
        initComponents();
        try {
            BufferedReader brSearch1 = new BufferedReader(new FileReader("MenuList.txt"));
            String key[] = new String[1024];
            String search;
            Object columns[] = {"Emp ID", "Name", "Salary", "Emp Shift"};
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columns);
            jTable1.setModel(model);
            Object row[] = new Object[4];
            while ((search = brSearch1.readLine()) != null) {
                key = search.split(",");
                row[0] = key[1];
                row[1] = key[2];
                row[2] = key[3];
                row[3] = key[4];
                model.addRow(row);
            }
            brSearch1.close();
        } catch (Exception ex) {
            System.out.println("Exception msg: " + ex);
        }
    }

    //String id, name, salary, shift;
    int cnt = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Delete Details");
        setPreferredSize(new java.awt.Dimension(594, 566));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(578, 532));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DELETE  DETAILS");
        jLabel1.setMaximumSize(new java.awt.Dimension(108, 29));
        jLabel1.setMinimumSize(new java.awt.Dimension(108, 29));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 40, 546, 38);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp ID", "Name", "Salary", "Emp Shift"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 210, 518, 337);

        jButton1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(220, 130, 103, 39);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-30, -120, 920, 930);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -5, 710, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String acc = model.getValueAt(i, 0).toString();
        ((DefaultTableModel)jTable1.getModel()).removeRow(i);//REMOVINF THE SELECTED ROW FROM THE TABLE
        ArrayList<String> tempArray = new ArrayList<>();
        ArrayList<String> tempArray2 = new ArrayList<>();
        ArrayList<String> tempArray3 = new ArrayList<>();
        try {
            try {
                FileReader fr = new FileReader("C:\\Users\\shreya kulkarni\\Documents\\NetBeansProjects\\Employee_Management_System\\Second_Index.txt");
                Scanner reader = new Scanner(fr);
                FileReader fr2 = new FileReader("C:\\Users\\shreya kulkarni\\Documents\\NetBeansProjects\\Employee_Management_System\\Index.txt");
                Scanner reader2 = new Scanner(fr2);
                FileReader fr3 = new FileReader("C:\\Users\\shreya kulkarni\\Documents\\NetBeansProjects\\Employee_Management_System\\MenuList.txt");
                Scanner reader3 = new Scanner(fr3);
                String line, val, result;
                String lineArr[], lineArr2[], lineArr3[];
                String recordsrch;
                while ((line = reader.nextLine()) != null && (result = reader3.nextLine()) != null && (val = reader2.nextLine()) != null) {
                    lineArr = line.split(",");
                    lineArr2 = val.split(",");
                    lineArr3 = result.split(",");
                    if (lineArr[0].equals(acc)) {
                        tempArray.isEmpty();
                    } else {
                        tempArray.add(line);
                    }
                    if (lineArr2[1].equals(acc)) {
                        tempArray2.isEmpty();
                    } else {
                        tempArray2.add(val);
                    }
                    if (lineArr3[1].equals(acc)) {
                        tempArray3.isEmpty();
                    } else {
                        tempArray3.add(result);
                    }
                }
                fr.close();
                fr2.close();
                fr3.close();
            } catch (Exception e) {
            }
        } catch (Exception e) {
        }
        try {
            try {
                PrintWriter pr = new PrintWriter("C:\\Users\\shreya kulkarni\\Documents\\NetBeansProjects\\Employee_Management_System\\Second_Index.txt");
                PrintWriter pr2 = new PrintWriter("C:\\Users\\shreya kulkarni\\Documents\\NetBeansProjects\\Employee_Management_System\\Index.txt");
                PrintWriter pr3 = new PrintWriter("C:\\Users\\shreya kulkarni\\Documents\\NetBeansProjects\\Employee_Management_System\\MenuList.txt");
                for (String str : tempArray) //it will take the values from temporary array and write in the secondary index.txt by taking values in string str
                {
                    pr.println(str);
                }
                for (String str2 : tempArray2) //it will take the values from temporary array and write in theindex.txt by taking values in string str2 
                {
                    pr2.println(str2);
                }
                for (String str3 : tempArray3)  //it will take the values from temporary array and write in the menulist.txt by taking values in string str3
                {
                    pr3.println(str3);
                }
                pr.close();
                pr2.close();
                pr3.close();
            } catch (Exception e) {
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
