
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        AddBtn = new javax.swing.JButton();
        SearchBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        SortBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employee Management");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        Desktop.setBackground(new java.awt.Color(255, 255, 255));
        Desktop.setPreferredSize(new java.awt.Dimension(1350, 710));

        AddBtn.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        AddBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddBtn.setText("ADD");
        AddBtn.setBorder(null);
        AddBtn.setContentAreaFilled(false);
        AddBtn.setMaximumSize(new java.awt.Dimension(85, 23));
        AddBtn.setMinimumSize(new java.awt.Dimension(85, 23));
        AddBtn.setPreferredSize(new java.awt.Dimension(85, 23));
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        Desktop.add(AddBtn);
        AddBtn.setBounds(70, 160, 130, 40);

        SearchBtn.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        SearchBtn.setForeground(new java.awt.Color(255, 255, 255));
        SearchBtn.setText("SEARCH");
        SearchBtn.setBorder(null);
        SearchBtn.setContentAreaFilled(false);
        SearchBtn.setMaximumSize(new java.awt.Dimension(85, 23));
        SearchBtn.setMinimumSize(new java.awt.Dimension(85, 23));
        SearchBtn.setPreferredSize(new java.awt.Dimension(85, 23));
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        Desktop.add(SearchBtn);
        SearchBtn.setBounds(80, 330, 150, 40);

        ViewBtn.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        ViewBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewBtn.setText("VIEW");
        ViewBtn.setBorder(null);
        ViewBtn.setContentAreaFilled(false);
        ViewBtn.setMaximumSize(new java.awt.Dimension(85, 23));
        ViewBtn.setMinimumSize(new java.awt.Dimension(85, 23));
        ViewBtn.setPreferredSize(new java.awt.Dimension(85, 23));
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });
        Desktop.add(ViewBtn);
        ViewBtn.setBounds(70, 240, 130, 40);

        UpdateBtn.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        UpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        UpdateBtn.setText("UPDATE");
        UpdateBtn.setBorder(null);
        UpdateBtn.setContentAreaFilled(false);
        UpdateBtn.setMaximumSize(new java.awt.Dimension(85, 23));
        UpdateBtn.setMinimumSize(new java.awt.Dimension(85, 23));
        UpdateBtn.setPreferredSize(new java.awt.Dimension(85, 23));
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        Desktop.add(UpdateBtn);
        UpdateBtn.setBounds(370, 160, 170, 40);

        DeleteBtn.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBtn.setText("DELETE");
        DeleteBtn.setBorder(null);
        DeleteBtn.setContentAreaFilled(false);
        DeleteBtn.setMaximumSize(new java.awt.Dimension(85, 23));
        DeleteBtn.setMinimumSize(new java.awt.Dimension(85, 23));
        DeleteBtn.setPreferredSize(new java.awt.Dimension(85, 23));
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        Desktop.add(DeleteBtn);
        DeleteBtn.setBounds(380, 240, 160, 40);

        SortBtn.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        SortBtn.setForeground(new java.awt.Color(255, 255, 255));
        SortBtn.setText("SORT");
        SortBtn.setBorder(null);
        SortBtn.setContentAreaFilled(false);
        SortBtn.setMaximumSize(new java.awt.Dimension(85, 23));
        SortBtn.setMinimumSize(new java.awt.Dimension(85, 23));
        SortBtn.setPreferredSize(new java.awt.Dimension(85, 23));
        SortBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortBtnActionPerformed(evt);
            }
        });
        Desktop.add(SortBtn);
        SortBtn.setBounds(390, 330, 130, 40);

        ExitBtn.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        ExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn.setText("EXIT");
        ExitBtn.setBorder(null);
        ExitBtn.setContentAreaFilled(false);
        ExitBtn.setMaximumSize(new java.awt.Dimension(85, 23));
        ExitBtn.setMinimumSize(new java.awt.Dimension(85, 23));
        ExitBtn.setPreferredSize(new java.awt.Dimension(85, 23));
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        Desktop.add(ExitBtn);
        ExitBtn.setBounds(180, 440, 229, 40);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EMPLOYEE MANAGEMENT SYSTEM");
        Desktop.add(jLabel2);
        jLabel2.setBounds(210, 10, 1000, 110);
        Desktop.add(jLabel3);
        jLabel3.setBounds(10, -20, 0, 1130);

        getContentPane().add(Desktop);
        Desktop.setBounds(0, 0, 1936, 1107);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        Add a = new Add();
        this.Desktop.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_AddBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        Search srch = new Search();
        this.Desktop.add(srch);
        srch.setVisible(true);
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        // TODO add your handling code here:
        View v = new View();
        this.Desktop.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
        Update u = new Update();
        this.Desktop.add(u);
        u.setVisible(true);
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        Delete del = new Delete();
        this.Desktop.add(del);
        del.setVisible(true);
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void SortBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortBtnActionPerformed
        // TODO add your handling code here:
        Sort srt = new Sort();
        this.Desktop.add(srt);
        srt.setVisible(true);
    }//GEN-LAST:event_SortBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JButton SortBtn;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
