
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Search extends javax.swing.JInternalFrame {

    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
    }
    String answer, id, name;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Search Details");
        setPreferredSize(new java.awt.Dimension(745, 645));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(578, 532));
        jPanel1.setLayout(null);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "NAME" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(34, 125, 120, 34);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SEARCH DETAILS");
        jLabel1.setMaximumSize(new java.awt.Dimension(108, 29));
        jLabel1.setMinimumSize(new java.awt.Dimension(108, 29));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 30, 385, 38);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(180, 120, 170, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(379, 121, 115, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp ID", "Name", "Salary", "Emp Shift"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(12, 189, 706, 337);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 750, 800);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            int flag = 0;
            int item = jComboBox1.getSelectedIndex();
            if (item == 0) {
                answer = jTextField1.getText().toUpperCase();
            } else {
                answer = jTextField1.getText().toUpperCase();
            }
            BufferedReader brSearch0 = new BufferedReader(new FileReader("Index.txt"));
            BufferedReader brSearch1 = new BufferedReader(new FileReader("MenuList.txt"));
            BufferedReader brSearch2 = new BufferedReader(new FileReader("Second_Index.txt"));
            String key[] = new String[1024];
            String key2[] = new String[1024];
            String key3[] = new String[1024];
            String search, val, result;
            Object columns[] = {"Emp ID", "Name", "Salary", "Emp Shift"};
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columns);
            jTable1.setModel(model);
            Object row[] = new Object[4];
            while ((search = brSearch0.readLine()) != null && (val = brSearch1.readLine()) != null && (result = brSearch2.readLine()) != null) {
                if (val.contains(answer))//if the answer (key entered) is present in the backend 
                {
                    key = val.split(",");
                    row[0] = key[1];
                    row[1] = key[2];
                    row[2] = key[3];
                    row[3] = key[4];
                    model.addRow(row);
                    flag = 1;
                    break;
                }
            }
            if (flag == 0) {
                JOptionPane.showMessageDialog(null, " does not exist");
            }
            brSearch0.close();
            brSearch1.close();
            brSearch2.close();
        } catch (Exception ex) {
            System.out.println("Exception msg: " + ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
